# server
server:
  port: 8888
spring:
  application:
    name: fzb_blog

  # datasource
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: fzb.0226
    driver-class-name: com.mysql.cj.jdbc.Driver
  # multipart
  servlet:
    multipart:
      # 单个文件最大值
      max-file-size: 5MB
      # 上传文件总的最大值
      max-request-size: 20MB

# mybatis.plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
  mapper-locations: classpath:com.BrantleyFan.blog.mapper/*.xml

# qiniu
qiniu:
  accessKey: 7SzE7Zod_2oDl0TeiuPRpx8wVT1bFZXBiiTXuJKw
  accessSecretKey: SExQcq0sh5P-S2wXleeMOSogJLarYK3E68H8nnvq
